# CodeDeployのデプロイ時の処理内容を定義
version: 0.0
os: linux
files:
  - source: / # デプロイ元
    destination: /home/webapp/menscosme

permissions:
  - object: /home/webapp/menscosme
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 120
      runas: webapp